In [1]:
import numpy as np
list=[1,2,3]
array=np.array(list)
print("list:",list)
print("array:",array)
type(list)
type(array)

list: [1, 2, 3]
array: [1 2 3]


numpy.ndarray

In [2]:
import numpy as np
list=[]
c=int(input("enter elements:"))
for i in range(c):
  d=int(input())
  list.append(d)
print(list)



enter elements:2
5
8
[5, 8]


In [3]:
type(list)

list

In [4]:
type(array)

numpy.ndarray

In [5]:
array1=[5,6,7]
array2=[8,9,6]
q=np.add(array1,array2)
print(q)
w=np.subtract(array1,array2)
print(w)
e=np.multiply(array1,array2)
print(e)
r=np.divide(array1,array2)
print(r)
t=np.power(array1,array2)
print(t)

[13 15 13]
[-3 -3  1]
[40 54 42]
[0.625      0.66666667 1.16666667]
[  390625 10077696   117649]


In [6]:
import numpy as np
l1=np.array(input())
l2=np.array(input())
print("array1",l1)
print("array2",l2)
new_array=np.char.add(l1,l2)
print("new array",new_array)



laxmi
govini
array1 laxmi
array2 govini
new array laxmigovini


In [7]:
import numpy as np
n=int(input("enter value:"))
g=np.sin(n)
print(g)
j=np.log(n)
print(j)
k=np.log2(n)
print(k)
p=np.exp(n)
print(p)

enter value:75
-0.38778163540943045
4.31748811353631
6.22881869049588
3.7332419967990015e+32
